// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-boiler/config"
	"go-boiler/server/http"
)

// Injectors from wire.go:

func InitializeService() *http.ServerHTTP {
	configConfig := config.InitializeConfiguration()
	serverHTTP := http.InitializeServer(configConfig)
	return serverHTTP
}
